[2025-04-22T17:04:06.802+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: gen_data_daily.gen_data_daily scheduled__2025-03-01T22:00:00+00:00 [queued]>
[2025-04-22T17:04:06.824+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: gen_data_daily.gen_data_daily scheduled__2025-03-01T22:00:00+00:00 [queued]>
[2025-04-22T17:04:06.824+0000] {taskinstance.py:2171} INFO - Starting attempt 3 of 4
[2025-04-22T17:04:06.859+0000] {taskinstance.py:2192} INFO - Executing <Task(BashOperator): gen_data_daily> on 2025-03-01 22:00:00+00:00
[2025-04-22T17:04:06.873+0000] {standard_task_runner.py:60} INFO - Started process 1752 to run task
[2025-04-22T17:04:06.881+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'gen_data_daily', 'gen_data_daily', 'scheduled__2025-03-01T22:00:00+00:00', '--job-id', '122', '--raw', '--subdir', 'DAGS_FOLDER/gen_data_daily.py', '--cfg-path', '/tmp/tmp1ylz35rc']
[2025-04-22T17:04:06.883+0000] {standard_task_runner.py:88} INFO - Job 122: Subtask gen_data_daily
[2025-04-22T17:04:07.055+0000] {task_command.py:423} INFO - Running <TaskInstance: gen_data_daily.gen_data_daily scheduled__2025-03-01T22:00:00+00:00 [running]> on host 45b38884c639
[2025-04-22T17:04:07.267+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:207: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2025-04-22T17:04:07.332+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='longnv' AIRFLOW_CTX_DAG_ID='gen_data_daily' AIRFLOW_CTX_TASK_ID='gen_data_daily' AIRFLOW_CTX_EXECUTION_DATE='2025-03-01T22:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-01T22:00:00+00:00'
[2025-04-22T17:04:07.333+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-04-22T17:04:07.334+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\n        python /opt/***/external_scripts/1_gen_transaction_data.py 2025-03-02\n        ']
[2025-04-22T17:04:07.357+0000] {subprocess.py:86} INFO - Output:
[2025-04-22T17:04:10.208+0000] {subprocess.py:93} INFO - Created log directory: /opt/***/logs/1_gen_transaction_data
[2025-04-22T17:04:10.343+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-04-22T17:04:10.420+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=gen_data_daily, task_id=gen_data_daily, execution_date=20250301T220000, start_date=20250422T170406, end_date=20250422T170410
[2025-04-22T17:04:10.520+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-04-22T17:04:10.876+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
