[2025-04-01T17:47:27.526+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: gen_data_daily.gen_data_daily scheduled__2025-03-14T22:00:00+00:00 [queued]>
[2025-04-01T17:47:27.542+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: gen_data_daily.gen_data_daily scheduled__2025-03-14T22:00:00+00:00 [queued]>
[2025-04-01T17:47:27.542+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 2
[2025-04-01T17:47:27.559+0000] {taskinstance.py:2192} INFO - Executing <Task(BashOperator): gen_data_daily> on 2025-03-14 22:00:00+00:00
[2025-04-01T17:47:27.566+0000] {standard_task_runner.py:60} INFO - Started process 830 to run task
[2025-04-01T17:47:27.572+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'gen_data_daily', 'gen_data_daily', 'scheduled__2025-03-14T22:00:00+00:00', '--job-id', '32', '--raw', '--subdir', 'DAGS_FOLDER/gen_data_daily.py', '--cfg-path', '/tmp/tmpggc2315l']
[2025-04-01T17:47:27.573+0000] {standard_task_runner.py:88} INFO - Job 32: Subtask gen_data_daily
[2025-04-01T17:47:27.660+0000] {task_command.py:423} INFO - Running <TaskInstance: gen_data_daily.gen_data_daily scheduled__2025-03-14T22:00:00+00:00 [running]> on host 0b0a92439eeb
[2025-04-01T17:47:27.822+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='longnv' AIRFLOW_CTX_DAG_ID='gen_data_daily' AIRFLOW_CTX_TASK_ID='gen_data_daily' AIRFLOW_CTX_EXECUTION_DATE='2025-03-14T22:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-14T22:00:00+00:00'
[2025-04-01T17:47:27.823+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-04-01T17:47:27.825+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\n        python /opt/***/external_scripts/1_gen_transaction_data.py 2025-03-15\n        ']
[2025-04-01T17:47:27.841+0000] {subprocess.py:86} INFO - Output:
[2025-04-01T17:47:28.922+0000] {subprocess.py:93} INFO - Successfully inserted 5000 rows into transaction_data table at 2025-03-15
[2025-04-01T17:47:28.923+0000] {subprocess.py:93} INFO - Table contains 70000 rows
[2025-04-01T17:47:28.923+0000] {subprocess.py:93} INFO - Data generation and insertion complete at 2025-03-15
[2025-04-01T17:47:29.045+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-04-01T17:47:29.141+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=gen_data_daily, task_id=gen_data_daily, execution_date=20250314T220000, start_date=20250401T174727, end_date=20250401T174729
[2025-04-01T17:47:29.202+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-04-01T17:47:29.224+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-28T17:08:58.890+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: gen_data_daily.gen_data_daily scheduled__2025-03-14T22:00:00+00:00 [queued]>
[2025-04-28T17:08:58.913+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: gen_data_daily.gen_data_daily scheduled__2025-03-14T22:00:00+00:00 [queued]>
[2025-04-28T17:08:58.914+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 2
[2025-04-28T17:08:58.934+0000] {taskinstance.py:2192} INFO - Executing <Task(BashOperator): gen_data_daily> on 2025-03-14 22:00:00+00:00
[2025-04-28T17:08:58.942+0000] {standard_task_runner.py:60} INFO - Started process 44377 to run task
[2025-04-28T17:08:58.948+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'gen_data_daily', 'gen_data_daily', 'scheduled__2025-03-14T22:00:00+00:00', '--job-id', '166', '--raw', '--subdir', 'DAGS_FOLDER/gen_data_daily.py', '--cfg-path', '/tmp/tmp5ehcs56m']
[2025-04-28T17:08:58.950+0000] {standard_task_runner.py:88} INFO - Job 166: Subtask gen_data_daily
[2025-04-28T17:08:59.062+0000] {task_command.py:423} INFO - Running <TaskInstance: gen_data_daily.gen_data_daily scheduled__2025-03-14T22:00:00+00:00 [running]> on host 45b38884c639
[2025-04-28T17:08:59.190+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:207: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2025-04-28T17:08:59.238+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='longnv' AIRFLOW_CTX_DAG_ID='gen_data_daily' AIRFLOW_CTX_TASK_ID='gen_data_daily' AIRFLOW_CTX_EXECUTION_DATE='2025-03-14T22:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-14T22:00:00+00:00'
[2025-04-28T17:08:59.241+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-04-28T17:08:59.243+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\n        python /opt/***/external_scripts/step_1_1_gen_transaction_data.py 2025-03-15\n        ']
[2025-04-28T17:08:59.277+0000] {subprocess.py:86} INFO - Output:
[2025-04-28T17:09:00.520+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-04-28T17:09:00.564+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=gen_data_daily, task_id=gen_data_daily, execution_date=20250314T220000, start_date=20250428T170858, end_date=20250428T170900
[2025-04-28T17:09:00.789+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-04-28T17:09:00.876+0000] {taskinstance.py:3281} INFO - 1 downstream tasks scheduled from follow-on schedule check
