[2025-04-02T16:02:39.817+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: gen_data_daily.gen_data_daily scheduled__2025-03-18T22:00:00+00:00 [queued]>
[2025-04-02T16:02:39.826+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: gen_data_daily.gen_data_daily scheduled__2025-03-18T22:00:00+00:00 [queued]>
[2025-04-02T16:02:39.827+0000] {taskinstance.py:2171} INFO - Starting attempt 2 of 3
[2025-04-02T16:02:39.840+0000] {taskinstance.py:2192} INFO - Executing <Task(BashOperator): gen_data_daily> on 2025-03-18 22:00:00+00:00
[2025-04-02T16:02:39.849+0000] {standard_task_runner.py:60} INFO - Started process 309 to run task
[2025-04-02T16:02:39.853+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'gen_data_daily', 'gen_data_daily', 'scheduled__2025-03-18T22:00:00+00:00', '--job-id', '59', '--raw', '--subdir', 'DAGS_FOLDER/gen_data_daily.py', '--cfg-path', '/tmp/tmpi8fm7j9x']
[2025-04-02T16:02:39.854+0000] {standard_task_runner.py:88} INFO - Job 59: Subtask gen_data_daily
[2025-04-02T16:02:39.919+0000] {task_command.py:423} INFO - Running <TaskInstance: gen_data_daily.gen_data_daily scheduled__2025-03-18T22:00:00+00:00 [running]> on host 4a8602fc40fd
[2025-04-02T16:02:39.977+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:207: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2025-04-02T16:02:40.015+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='longnv' AIRFLOW_CTX_DAG_ID='gen_data_daily' AIRFLOW_CTX_TASK_ID='gen_data_daily' AIRFLOW_CTX_EXECUTION_DATE='2025-03-18T22:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-18T22:00:00+00:00'
[2025-04-02T16:02:40.017+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-04-02T16:02:40.017+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\n        python /opt/***/external_scripts/1_gen_transaction_data.py 2025-03-19\n        ']
[2025-04-02T16:02:40.031+0000] {subprocess.py:86} INFO - Output:
[2025-04-02T16:02:40.872+0000] {subprocess.py:93} INFO - Successfully inserted 5000 rows into transaction_data table at 2025-03-19
[2025-04-02T16:02:40.872+0000] {subprocess.py:93} INFO - Table contains 85000 rows
[2025-04-02T16:02:40.872+0000] {subprocess.py:93} INFO - Data generation and insertion complete at 2025-03-19
[2025-04-02T16:02:40.962+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-04-02T16:02:41.014+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=gen_data_daily, task_id=gen_data_daily, execution_date=20250318T220000, start_date=20250402T160239, end_date=20250402T160241
[2025-04-02T16:02:41.083+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-04-02T16:02:41.102+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
