[2025-04-02T16:02:17.395+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: gen_data_daily.gen_data_daily scheduled__2025-03-08T22:00:00+00:00 [queued]>
[2025-04-02T16:02:17.407+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: gen_data_daily.gen_data_daily scheduled__2025-03-08T22:00:00+00:00 [queued]>
[2025-04-02T16:02:17.408+0000] {taskinstance.py:2171} INFO - Starting attempt 2 of 3
[2025-04-02T16:02:17.422+0000] {taskinstance.py:2192} INFO - Executing <Task(BashOperator): gen_data_daily> on 2025-03-08 22:00:00+00:00
[2025-04-02T16:02:17.429+0000] {standard_task_runner.py:60} INFO - Started process 202 to run task
[2025-04-02T16:02:17.434+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'gen_data_daily', 'gen_data_daily', 'scheduled__2025-03-08T22:00:00+00:00', '--job-id', '50', '--raw', '--subdir', 'DAGS_FOLDER/gen_data_daily.py', '--cfg-path', '/tmp/tmp8shzmd58']
[2025-04-02T16:02:17.436+0000] {standard_task_runner.py:88} INFO - Job 50: Subtask gen_data_daily
[2025-04-02T16:02:17.527+0000] {task_command.py:423} INFO - Running <TaskInstance: gen_data_daily.gen_data_daily scheduled__2025-03-08T22:00:00+00:00 [running]> on host 4a8602fc40fd
[2025-04-02T16:02:17.643+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:207: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2025-04-02T16:02:17.691+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='longnv' AIRFLOW_CTX_DAG_ID='gen_data_daily' AIRFLOW_CTX_TASK_ID='gen_data_daily' AIRFLOW_CTX_EXECUTION_DATE='2025-03-08T22:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-08T22:00:00+00:00'
[2025-04-02T16:02:17.692+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-04-02T16:02:17.693+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\n        python /opt/***/external_scripts/1_gen_transaction_data.py 2025-03-09\n        ']
[2025-04-02T16:02:17.724+0000] {subprocess.py:86} INFO - Output:
[2025-04-02T16:02:18.815+0000] {subprocess.py:93} INFO - Successfully inserted 5000 rows into transaction_data table at 2025-03-09
[2025-04-02T16:02:18.816+0000] {subprocess.py:93} INFO - Table contains 40000 rows
[2025-04-02T16:02:18.816+0000] {subprocess.py:93} INFO - Data generation and insertion complete at 2025-03-09
[2025-04-02T16:02:18.955+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-04-02T16:02:18.993+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=gen_data_daily, task_id=gen_data_daily, execution_date=20250308T220000, start_date=20250402T160217, end_date=20250402T160218
[2025-04-02T16:02:19.071+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-04-02T16:02:19.091+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
